/*  THIS FILE WAS GENERATED BY THE DATALIGHT RELIANCE EDGE CONFIGURATION
    UTILITY.  DO NOT MODIFY.

    Generated by configuration utility version 2.02
*/
/** @file
*/
#include <redconf.h>
#include <redtypes.h>
#include <redmacs.h>
#include <redvolume.h>


const VOLCONF gaRedVolConf[REDCONF_VOLUME_COUNT] =
{
    { 4096U, 496U, 0U, false, 100U, 0U, "internal" },
    { 4096U, 4096U, 0U, false, 100U, 0U, "external" },
};
